### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by biebricher-of** [thomasrawiel/hreflang-pages#1]
Hi,

thank you for the Extension! :)

We use it under TYPO3 11.5 and PHP8.2 and it need some compatibility fixes. 

In PHP 8.2 there are some changes:
`Deprecated ${} string interpolation.`

To make the Extension compatible - two changes are needed.

File: hreflang-pages/Classes/Utility/HreflangListUtility.php
Line: 144: ${hreflang} ==> {$hreflang} / ${url} ==> {$url}
old: `                $content .= "<li><strong>${hreflang}</strong> (${url})</li>";`
new: `                $content .= "<li><strong>{$hreflang}</strong> ({$url})</li>";`

File: hreflang-pages/Configuration/TCA/Overrides/pages.php 
Line: 108:
old: `        "--div--;${LLL}div.hreflang,`
new: `        "--div--;{$LLL}div.hreflang,`

Kind Regards,
Carsten

**Comment by thomasrawiel** [comment]
Hi,
thanks for the report. The issue has been fixed. Please update to `1.1.0` or use `dev-main`

Cheers

**Comment by thomasrawiel** [comment]
@biebricher-of PS: if you're interested, there's also https://packagist.org/packages/traw/hreflang-news for EXT:news (still in beta, though)
